#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @file
# @author (C) 2015 by Roman Khassraf <rkhassraf@gmail.com>
#         (C) 2018 by Piotr Krysik <ptrkrysik@gmail.com>
# @section LICENSE
#
# Gr-gsm is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# Gr-gsm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gr-gsm; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#
#

from gnuradio import gr
from gnuradio import blocks
from gnuradio import eng_notation
from gnuradio.eng_option import eng_option
from optparse import OptionParser

import grgsm
import osmosdr
import pmt
import signal
import sys

class grgsm_capture(gr.top_block):
    def __init__(self,
                 freq,
                 gain=30,
                 bb_gain=20,
                 if_gain=20,
                 samp_rate=1e6,
                 freq_corr=0,
                 output_file_name=None,
                 rec_length=float('Inf'),
                 bandwidth=0,
                 device_args=""):
        gr.top_block.__init__(self, "Gr-gsm Capture")

        ##################################################
        # Parameters
        ##################################################
        self.freq = freq
        self.gain = gain
        self.bb_gain = bb_gain
        self.if_gain = if_gain
        self.samp_rate = samp_rate
        self.freq_corr = freq_corr
        self.output_file_name = output_file_name
        self.rec_length = rec_length
        self.bandwidth = bandwidth

        ##################################################
        # Processing Blocks
        ##################################################

        self.rtlsdr_source = \
                    osmosdr.source(args="numchan=" + str(1) + " " + device_args )
        self.set_samp_rate(samp_rate)
        self.set_freq(freq)
        self.set_freq_corr(freq_corr)
        self.rtlsdr_source.set_dc_offset_mode(2, 0)
        self.rtlsdr_source.set_iq_balance_mode(2, 0)
        self.rtlsdr_source.set_gain_mode(True, 0)
        self.rtlsdr_source.set_gain(gain, 0)
        self.rtlsdr_source.set_if_gain(if_gain, 0)
        self.rtlsdr_source.set_bb_gain(bb_gain, 0)
        self.rtlsdr_source.set_antenna("", 0)
        self.rtlsdr_source.set_bandwidth(bandwidth, 0)

        if self.rec_length != float('Inf'):
            self.head = \
                    blocks.head(gr.sizeof_gr_complex, int(samp_rate*rec_length))

        if self.output_file_name:
            self.file_sink = blocks.file_sink(gr.sizeof_gr_complex*1, \
                                              self.output_file_name, False)
            self.file_sink.set_unbuffered(False)

        ##################################################
        # Connections
        ##################################################

        if self.rec_length != float('Inf'): #if recording length is not infinite connect head block after the source
            self.connect((self.rtlsdr_source, 0), (self.head, 0))
            self.connect((self.head, 0), (self.file_sink, 0))
        else:
            self.connect((self.rtlsdr_source, 0), (self.file_sink, 0))

    def get_freq(self):
        return self.freq

    def set_freq(self, freq):
        self.freq = freq
        self.rtlsdr_source.set_center_freq(freq, 0)

    def get_arfcn(self):
        return self.arfcn

    def set_arfcn(self, arfcn):
        self.arfcn = arfcn

    def get_gain(self):
        return self.gain

    def set_gain(self, gain):
        self.rtlsdr_source.set_gain(gain, 0)
        self.gain = gain

    def set_bb_gain(self, bb_gain):
        self.rtlsdr_source.set_bb_gain(bb_gain, 0)
        self.bb_gain = bb_gain

    def get_bb_gain(self):
        return self.bb_gain

    def set_if_gain(self, if_gain):
        self.rtlsdr_source.set_if_gain(if_gain, 0)
        self.if_gain = if_gain

    def get_if_gain(self):
        return self.if_gain

    def get_samp_rate(self):
        return self.samp_rate

    def set_samp_rate(self, samp_rate):
        self.samp_rate = samp_rate
        self.rtlsdr_source.set_sample_rate(self.samp_rate)

    def get_freq_corr(self):
        return self.freq_corr

    def set_freq_corr(self, freq_corr):
        self.freq_corr = freq_corr
        self.rtlsdr_source.set_freq_corr(freq_corr, 0)

    def get_rec_length(self):
        return self.rec_length

    def set_rec_length(self, rec_length):
        self.rec_length = rec_length
        self.head.set_length(int(self.samp_rate*self.rec_length))

if __name__ == '__main__':

    parser = OptionParser(option_class=eng_option, usage="%prog [options] output_file_name",
                          description="RTL-SDR capturing app of gr-gsm.")

    parser.add_option("-f", "--freq", dest="freq", type="eng_float",
                      help="Set frequency [default=%default]")

    parser.add_option("-a", "--arfcn", dest="arfcn", type="intx", 
                      help="Set ARFCN instead of frequency (for PCS1900 add"
                           "0x8000 (2**15) to the ARFCN number)")

    parser.add_option("-g", "--gain", dest="gain", type="eng_float",
                      default=eng_notation.num_to_str(30),
                      help="Set gain [default=%default]")

    parser.add_option("-s", "--samp-rate", dest="samp_rate", type="eng_float",
                      default=eng_notation.num_to_str(1000000),
                      help="Set samp_rate [default=%default]")

    parser.add_option("-c", "--output_file_name", dest="output_file_name",
                      help="File where the captured data are saved")

    parser.add_option("-T", "--rec-length", dest="rec_length", type="eng_float",
                      default=eng_notation.num_to_str(float('Inf')),
                      help="Set length of recording in seconds"
                      "[default=infinity]")

    parser.add_option("-p", "--freq-corr", dest="freq_corr", type="eng_float",
                      default="0", help="Set frequency correction in"
                      " ppm [default=%default]")

    parser.add_option("-w", "--bandwidth", dest="bandwidth", type="eng_float",
                      default="0", help="Set bandwidth [default=samp_rate]")

    parser.add_option("", "--bb-gain", dest="bb_gain", type="eng_float",
                      default=eng_notation.num_to_str(20),
                      help="Set baseband gain [default=%default]")

    parser.add_option("", "--if-gain", dest="if_gain", type="eng_float",
                      default=eng_notation.num_to_str(20),
                      help="Set intermediate freque gain [default=%default]")

    parser.add_option("", "--args", dest="device_args", type="string",
                      default="", help="Set device arguments"
                      "[default=%default]")

    (options, args) = parser.parse_args()

    if not args:
        parser.error("Please provide an output file name to save the captured data\n")

    output_file_name = args[0]

    if (options.freq is None and options.arfcn is None) or \
       (options.freq is not None and options.arfcn is not None):
        parser.error("You have to provide either a frequency or"
                     "an ARFCN (but not both).\n")

    arfcn = 0
    freq = 0
    if options.arfcn:
        if not grgsm.arfcn.is_valid_arfcn(options.arfcn):
            parser.error("ARFCN is not valid\n")
        else:
            freq = grgsm.arfcn.arfcn2downlink(options.arfcn)
    elif options.freq:
        freq = options.freq

    tb = grgsm_capture(freq=freq,
                       gain=options.gain,
                       bb_gain=options.bb_gain,
                       if_gain=options.if_gain,
                       samp_rate=options.samp_rate,
                       freq_corr=options.freq_corr,
                       output_file_name=output_file_name,
                       rec_length=options.rec_length,
                       device_args=options.device_args)

    def signal_handler(signal, frame):
        tb.stop()
        tb.wait()
        sys.exit(0)

    signal.signal(signal.SIGINT, signal_handler)

    tb.start()
    tb.wait()
